---
- name: download Homebrew install script
  get_url:
    url=https://raw.githubusercontent.com/Homebrew/install/master/install
    dest=vendor/homebrew/install

- name: install Homebrew
  command: ruby vendor/homebrew/install creates=/usr/local/bin/brew

- name: update Homebrew
  homebrew: update_homebrew=yes

- name: tap brewdler
  homebrew_tap: tap=homebrew/brewdler state=present

- name: brewdle
  command: brew brewdle chdir=roles/homebrew/files

- name: clean up old versions
  command: brew cleanup

- name: clean up old casks
  command: brew cask cleanup