---
- name: clone zsh-autosuggest
  git: repo=https://github.com/tarruda/zsh-autosuggestions.git dest=~/.zsh/zsh-autosuggestions

- name: Symlink dotfiles
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
    dest=~/{{ item }}
    state=link
    force=yes
  with_items:
    - .vimrc
    - .gemrc
    - .tmux.conf
    - .zshrc
    - .gitconfig
    - .gitignore_global
    - .git_template
    - .agignore

- name: Add sensitive dotfiles
  copy: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
    dest=~/{{ item }}
    force=no
  with_items:
    - .identity
    - .gitconfig_identity
