---
- name: show the ~/Library folder
  command: chflags nohidden ~/Library
  
- name: don't automatically rearrange Spaces based on most recent use
  command: defaults write com.apple.dock mru-spaces -bool false
  
- name: increase the window resize speed for Cocoa applications
  command: defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
  
- name: Disable smart quote
  command: defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

- name: Disable smart dash
  command: defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

- name: Disable auto-correct
  command: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
  
- name: Do not write .DS_Store on network volumes
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: Do not write .DS_Store on USB volumes
  command: defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
  
- name: Disable the 'Are you sure you want to open this application?' dialog
  command: defaults write com.apple.LaunchServices LSQuarantine -bool false

- name: Expand save panel by default
  shell: |
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true 
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

- name: Save to disk (not to iCloud) by default
  command: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Finder

- name: Finder | Show path bar
  command: defaults write com.apple.finder ShowPathbar -bool true

- name: Finder | Show status bar
  command: defaults write com.apple.finder ShowStatusBar -bool true

- name: Finder | Keep folder on top when sorting by name
  command: defaults write com.apple.finder _FXSortFoldersFirst -bool true
  
- name: Finder | Remove the spring loading delay for directories
  command: defaults write NSGlobalDomain com.apple.springing.delay -float 0

- name: Finder | Disable window animations
  command: defaults write com.apple.finder DisableAllAnimations -bool true
  
- name: Finder | Show all filename extensions
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  
- name: Use list view in all Finder windows by default 
  command: defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Dock

- name: Dock | Speed up expose animation  
  command: defaults write com.apple.dock expose-animation-duration -float 0.1

- name: Dock | Disable grouping
  command: defaults write com.apple.dock "expose-group-by-app" -bool false
  
- name: Dock | Don't animate opening
  command: defaults write com.apple.dock launchanim -bool false

- name: Dock | Remove the animation when hiding/showing the Dock
  command: defaults write com.apple.dock autohide-time-modifier -float 0

- name: Dock | Automatically hide and show the Dock
  command: defaults write com.apple.dock autohide -bool true

# Activity Monitor

- name: Activity Monitor | Visualize CPU usage in the Activity Monitor Dock icon
  command: defaults write com.apple.ActivityMonitor IconType -int 5
  
- name: Show all processes in Activity Monitor
  command: defaults write com.apple.ActivityMonitor ShowCategory -int 0

- name: Trackpad | Bottom right corder is right-click
  shell: |
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
    defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
    defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

- name: Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
  command: defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

- name: Disable press-and-hold for keys in favor of key repeat
  command: defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

- name: Set a blazingly fast keyboard repeat rate
  shell: |
    defaults write NSGlobalDomain KeyRepeat -int 1
    defaults write NSGlobalDomain InitialKeyRepeat -int 10
    
- name: Require password immediately after sleep or screen saver begins
  shell: |
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int 0

# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
- name: Enable subpixel font rendering on non-Apple LCDs
  command: defaults write NSGlobalDomain AppleFontSmoothing -int 1
