tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/brewdler'
tap 'homebrew/versions'
tap 'homebrew/science'

brew 'ctags'
brew 'fzf'
brew 'git', args: ['with-pcre']
brew 'gnupg'
brew 'reattach-to-user-namespace'
brew 'openssl'
brew 'pstree'
brew 'tmux'
brew 'v8'
brew 'vim', args:['with-client-server']
brew 'wget'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'the_silver_searcher'
brew 'hub'
brew 'gnuplot', args: ['with-qt']
brew 'fontconfig', args: ['universal']
brew 'gsl'
brew 'graphviz'
brew 'ccat'
brew 'z'
brew 'fzf'
